apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
spec:
  #replicas: 1  #Por padrão já é um
  selector:
    matchLabels:
      app: db-noticias
  template:
    metadata:
      name: db-noticias
      labels:
        app: db-noticias
    spec:
      containers:
        - image: aluracursos/mysql-db:1
          name: db-noticias-container
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: db-configmap